language: go

go:
  - "1.6" # xenial
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.x"
  - "master"

matrix:
  allow_failures:
    - go: "master"
  fast_finish: true

addons:
  apt:
    packages:
      - libc-dev

before_install:
  - "go get -u github.com/golang/dep/cmd/dep"

before_script:
  - "dep ensure -vendor-only"

script: go test